package com.whitehat.platform.config;

import com.baomidou.mybatisplus.core.toolkit.Wrappers; import com.whitehat.platform.domain.*; import com.whitehat.platform.mapper.*;
import org.springframework.boot.CommandLineRunner; import org.springframework.beans.factory.annotation.Value; import org.springframework.core.annotation.Order; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Component;
import java.math.BigDecimal; import java.time.*;

@Component @Order(0) public class DataInitializer implements CommandLineRunner {
 private final UserMapper users; private final CompanyMapper companies; private final SecurityTaskMapper tasks; private final ForumPostMapper posts; private final PasswordEncoder encoder;
 @Value("${ADMIN_PASSWORD:Admin@123456}") String adminPassword; @Value("${WHITEHAT_PASSWORD:WhiteHat@123}") String whitehatPassword; @Value("${COMPANY_PASSWORD:Company@123}") String companyPassword;
 DataInitializer(UserMapper u,CompanyMapper c,SecurityTaskMapper t,ForumPostMapper p,PasswordEncoder e){users=u;companies=c;tasks=t;posts=p;encoder=e;}
 @Override public void run(String... args){User admin=ensure("admin",adminPassword,"平台管理员","ADMIN",5000,"安全治理,风险控制");User company=ensure("acme",companyPassword,"星云科技安全部","COMPANY",0,"");User whitehat=ensure("whitehat",whitehatPassword,"零日猎手","WHITEHAT",860,"Web安全,渗透测试,云安全");Company c=companies.selectOne(Wrappers.<Company>lambdaQuery().eq(Company::getAdminUserId,company.getId()));if(c==null){c=new Company();c.setAdminUserId(company.getId());c.setName("星云科技");c.setCreditCode("91310000DEMO2026");c.setDescription("专注云原生与企业协同服务");c.setStatus("APPROVED");c.setCreatedAt(OffsetDateTime.now());companies.insert(c);}if(tasks.selectCount(null)==0){seedTask(c,"核心业务 API 渗透测试","PENETRATION",new BigDecimal("12000"),"ADVANCED",14);seedTask(c,"云资产漏洞赏金计划","BUG_BOUNTY",new BigDecimal("30000"),"EXPERT",30);seedTask(c,"移动端安全审计","SECURITY_AUDIT",new BigDecimal("8000"),"INTERMEDIATE",8);}if(posts.selectCount(null)==0){ForumPost p=new ForumPost();p.setAuthorId(whitehat.getId());p.setCategory("Web安全");p.setTitle("从一次越权漏洞看 API 鉴权边界");p.setContent("复盘一次真实测试中发现的对象级授权缺失，以及如何系统化验证横向越权。");p.setViewCount(328);p.setLikeCount(42);p.setCreatedAt(OffsetDateTime.now().minusHours(3));p.setUpdatedAt(p.getCreatedAt());posts.insert(p);}}
 private User ensure(String name,String pass,String nick,String role,int score,String skills){User u=users.selectOne(Wrappers.<User>lambdaQuery().eq(User::getUsername,name));if(u!=null)return u;u=new User();u.setUsername(name);u.setPasswordHash(encoder.encode(pass));u.setNickname(nick);u.setRole(role);u.setScore(score);u.setLevelId(score>=4000?5L:score>=1500?4L:score>=500?3L:score>=100?2L:1L);u.setSkills(skills);u.setStatus("ACTIVE");u.setCreatedAt(OffsetDateTime.now());u.setUpdatedAt(OffsetDateTime.now());users.insert(u);return u;}
 private void seedTask(Company c,String title,String type,BigDecimal reward,String difficulty,int days){SecurityTask t=new SecurityTask();t.setTaskNo("TASK-DEMO-"+(tasks.selectCount(null)+1));t.setCompanyId(c.getId());t.setTitle(title);t.setType(type);t.setDescription("对授权范围内的目标开展安全测试，输出可复现、可修复的漏洞报告。");t.setTargetAssets("*.demo.example.com（仅限授权测试环境）");t.setStartDate(LocalDate.now());t.setEndDate(LocalDate.now().plusDays(days));t.setRewardAmount(reward);t.setDifficulty(difficulty);t.setMinSeverity("MEDIUM");t.setMemberLimit(20);t.setStatus("OPEN");t.setCreatedAt(OffsetDateTime.now());tasks.insert(t);}
}
