package com.whitehat.platform.service;

import com.baomidou.mybatisplus.core.metadata.IPage; import com.baomidou.mybatisplus.core.toolkit.Wrappers; import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.whitehat.platform.common.BusinessException; import com.whitehat.platform.domain.*; import com.whitehat.platform.dto.Requests; import com.whitehat.platform.mapper.*;
import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.time.*; import java.time.format.DateTimeFormatter; import java.util.*;

@Service public class PlatformService {
 private final UserMapper users; private final CompanyMapper companies; private final SecurityTaskMapper tasks; private final TaskMemberMapper members; private final DailyReportMapper reports; private final VulnerabilityReportMapper vulns; private final ScoreRecordMapper scores; private final ForumPostMapper posts; private final ForumCommentMapper comments;
 public PlatformService(UserMapper u,CompanyMapper c,SecurityTaskMapper t,TaskMemberMapper m,DailyReportMapper d,VulnerabilityReportMapper v,ScoreRecordMapper s,ForumPostMapper p,ForumCommentMapper fc){users=u;companies=c;tasks=t;members=m;reports=d;vulns=v;scores=s;posts=p;comments=fc;}
 public Map<String,Object> dashboard(){return Map.of("whitehats",users.selectCount(Wrappers.<User>lambdaQuery().eq(User::getRole,"WHITEHAT")),"companies",companies.selectCount(null),"vulnerabilities",vulns.selectCount(null),"completedTasks",tasks.selectCount(Wrappers.<SecurityTask>lambdaQuery().eq(SecurityTask::getStatus,"COMPLETED")),"activeTasks",tasks.selectCount(Wrappers.<SecurityTask>lambdaQuery().in(SecurityTask::getStatus,List.of("OPEN","IN_PROGRESS"))));}
 public IPage<SecurityTask> taskPage(int page,int size,String keyword,String type){var q=Wrappers.<SecurityTask>lambdaQuery().in(SecurityTask::getStatus,List.of("OPEN","IN_PROGRESS"));if(keyword!=null&&!keyword.isBlank())q.and(x->x.like(SecurityTask::getTitle,keyword).or().like(SecurityTask::getDescription,keyword));if(type!=null&&!type.isBlank())q.eq(SecurityTask::getType,type);q.orderByDesc(SecurityTask::getCreatedAt);return tasks.selectPage(Page.of(page,size),q);}
 public SecurityTask task(Long id){SecurityTask t=tasks.selectById(id);if(t==null)throw new BusinessException("任务不存在");return t;}
 @Transactional public SecurityTask createTask(Long uid,Requests.TaskCreate r){Company c=companies.selectOne(Wrappers.<Company>lambdaQuery().eq(Company::getAdminUserId,uid));if(c==null||!"APPROVED".equals(c.getStatus()))throw new BusinessException("企业尚未通过认证");if(r.endDate().isBefore(r.startDate()))throw new BusinessException("结束日期不能早于开始日期");SecurityTask t=new SecurityTask();t.setTaskNo("TASK-"+LocalDate.now().format(DateTimeFormatter.BASIC_ISO_DATE)+"-"+UUID.randomUUID().toString().substring(0,6).toUpperCase());t.setCompanyId(c.getId());t.setTitle(r.title());t.setType(r.type());t.setDescription(r.description());t.setTargetAssets(r.targetAssets());t.setStartDate(r.startDate());t.setEndDate(r.endDate());t.setRewardAmount(r.rewardAmount());t.setDifficulty(r.difficulty());t.setMinSeverity(r.minSeverity());t.setMemberLimit(r.memberLimit());t.setStatus("OPEN");t.setCreatedAt(OffsetDateTime.now());tasks.insert(t);return t;}
 @Transactional public TaskMember apply(Long uid,Requests.TaskApply r){SecurityTask t=task(r.taskId());if(!"OPEN".equals(t.getStatus()))throw new BusinessException("任务当前不可申请");long count=members.selectCount(Wrappers.<TaskMember>lambdaQuery().eq(TaskMember::getTaskId,t.getId()).ne(TaskMember::getStatus,"REJECTED"));if(count>=t.getMemberLimit())throw new BusinessException("参与人数已满");TaskMember m=new TaskMember();m.setTaskId(t.getId());m.setUserId(uid);m.setApplyMessage(r.message());m.setStatus("APPROVED");m.setJoinedAt(OffsetDateTime.now());members.insert(m);return m;}
 public List<SecurityTask> myTasks(Long uid,String role){if("ADMIN".equals(role))return tasks.selectList(Wrappers.<SecurityTask>lambdaQuery().orderByDesc(SecurityTask::getCreatedAt));if("COMPANY".equals(role)){Company c=companies.selectOne(Wrappers.<Company>lambdaQuery().eq(Company::getAdminUserId,uid));return c==null?List.of():tasks.selectList(Wrappers.<SecurityTask>lambdaQuery().eq(SecurityTask::getCompanyId,c.getId()).orderByDesc(SecurityTask::getCreatedAt));}List<Long> ids=members.selectList(Wrappers.<TaskMember>lambdaQuery().eq(TaskMember::getUserId,uid)).stream().map(TaskMember::getTaskId).toList();return ids.isEmpty()?List.of():tasks.selectBatchIds(ids);}
 @Transactional public DailyReport daily(Long uid,Requests.Daily r){TaskMember m=members.selectOne(Wrappers.<TaskMember>lambdaQuery().eq(TaskMember::getTaskId,r.taskId()).eq(TaskMember::getUserId,uid).eq(TaskMember::getStatus,"APPROVED"));if(m==null)throw new BusinessException("您不是该任务的有效成员");DailyReport d=new DailyReport();d.setTaskMemberId(m.getId());d.setReportDate(r.reportDate());d.setWorkContent(r.workContent());d.setTestTarget(r.testTarget());d.setFindings(r.findings());d.setRiskAnalysis(r.riskAnalysis());d.setNextPlan(r.nextPlan());d.setAttachmentUrl(r.attachmentUrl());d.setCreatedAt(OffsetDateTime.now());reports.insert(d);return d;}
 public List<DailyReport> taskReports(Long uid,Long taskId){assertTaskManager(uid,taskId);List<Long> ids=members.selectList(Wrappers.<TaskMember>lambdaQuery().eq(TaskMember::getTaskId,taskId)).stream().map(TaskMember::getId).toList();return ids.isEmpty()?List.of():reports.selectList(Wrappers.<DailyReport>lambdaQuery().in(DailyReport::getTaskMemberId,ids).orderByDesc(DailyReport::getReportDate));}
 @Transactional public VulnerabilityReport createVulnerability(Long uid,Requests.VulnerabilityCreate r){if(members.selectCount(Wrappers.<TaskMember>lambdaQuery().eq(TaskMember::getTaskId,r.taskId()).eq(TaskMember::getUserId,uid).eq(TaskMember::getStatus,"APPROVED"))==0)throw new BusinessException("您不是该任务的有效成员");VulnerabilityReport v=new VulnerabilityReport();v.setReportNo("VUL-"+System.currentTimeMillis());v.setTaskId(r.taskId());v.setSubmitterId(uid);v.setTitle(r.title());v.setVulnerabilityType(r.vulnerabilityType());v.setAffectedAsset(r.affectedAsset());v.setDescription(r.description());v.setReproductionSteps(r.reproductionSteps());v.setPocAttachmentUrl(r.pocAttachmentUrl());v.setSeverity(r.severity());v.setCvssScore(r.cvssScore());v.setStatus("SUBMITTED");v.setCreatedAt(OffsetDateTime.now());vulns.insert(v);return v;}
 public List<VulnerabilityReport> vulnerabilities(Long uid,String role){if("ADMIN".equals(role))return vulns.selectList(Wrappers.<VulnerabilityReport>lambdaQuery().orderByDesc(VulnerabilityReport::getCreatedAt));if("COMPANY".equals(role)){Company c=companies.selectOne(Wrappers.<Company>lambdaQuery().eq(Company::getAdminUserId,uid));if(c==null)return List.of();List<Long> ids=tasks.selectList(Wrappers.<SecurityTask>lambdaQuery().eq(SecurityTask::getCompanyId,c.getId())).stream().map(SecurityTask::getId).toList();return ids.isEmpty()?List.of():vulns.selectList(Wrappers.<VulnerabilityReport>lambdaQuery().in(VulnerabilityReport::getTaskId,ids).orderByDesc(VulnerabilityReport::getCreatedAt));}return vulns.selectList(Wrappers.<VulnerabilityReport>lambdaQuery().eq(VulnerabilityReport::getSubmitterId,uid).orderByDesc(VulnerabilityReport::getCreatedAt));}
 @Transactional public VulnerabilityReport review(Long uid,Long id,Requests.VulnerabilityReview r){VulnerabilityReport v=vulns.selectById(id);if(v==null)throw new BusinessException("漏洞报告不存在");assertTaskManager(uid,v.getTaskId());if(List.of("CONFIRMED","REJECTED").contains(v.getStatus()))throw new BusinessException("报告已完成终审");v.setStatus(r.status());v.setReviewComment(r.reviewComment());if(r.severity()!=null)v.setSeverity(r.severity());v.setReviewedBy(uid);v.setReviewedAt(OffsetDateTime.now());vulns.updateById(v);if("CONFIRMED".equals(r.status()))award(v);return v;}
 private void award(VulnerabilityReport v){int delta=Map.of("LOW",10,"MEDIUM",50,"HIGH",200,"CRITICAL",500).getOrDefault(v.getSeverity(),0);ScoreRecord s=new ScoreRecord();s.setUserId(v.getSubmitterId());s.setDelta(delta);s.setSourceType("VULNERABILITY");s.setSourceId(v.getId());s.setDescription("漏洞 "+v.getReportNo()+" 确认奖励");s.setCreatedAt(OffsetDateTime.now());scores.insert(s);User u=users.selectById(v.getSubmitterId());u.setScore(u.getScore()+delta);u.setLevelId(levelFor(u.getScore()));u.setUpdatedAt(OffsetDateTime.now());users.updateById(u);}
 private long levelFor(int score){return score>=4000?5:score>=1500?4:score>=500?3:score>=100?2:1;}
 private void assertTaskManager(Long uid,Long taskId){SecurityTask t=task(taskId);Company c=companies.selectById(t.getCompanyId());User u=users.selectById(uid);if(!"ADMIN".equals(u.getRole())&&(c==null||!uid.equals(c.getAdminUserId())))throw new BusinessException("无权管理该任务");}
 public Map<String,Object> profile(Long uid){User u=users.selectById(uid);long rank=users.selectCount(Wrappers.<User>lambdaQuery().eq(User::getRole,"WHITEHAT").gt(User::getScore,u.getScore()))+1;return Map.of("id",u.getId(),"username",u.getUsername(),"nickname",u.getNickname(),"role",u.getRole(),"score",u.getScore(),"levelId",u.getLevelId(),"rank",rank,"skills",u.getSkills()==null?"":u.getSkills(),"completedTasks",members.selectCount(Wrappers.<TaskMember>lambdaQuery().eq(TaskMember::getUserId,uid).eq(TaskMember::getStatus,"COMPLETED")),"vulnerabilities",vulns.selectCount(Wrappers.<VulnerabilityReport>lambdaQuery().eq(VulnerabilityReport::getSubmitterId,uid)));}
 public List<User> rank(){return users.selectList(Wrappers.<User>lambdaQuery().eq(User::getRole,"WHITEHAT").select(User::getId,User::getNickname,User::getScore,User::getLevelId,User::getSkills,User::getAvatarUrl).orderByDesc(User::getScore).last("LIMIT 20"));}
 public List<Map<String,Object>> forumPosts(){return posts.selectList(Wrappers.<ForumPost>lambdaQuery().orderByDesc(ForumPost::getCreatedAt).last("LIMIT 50")).stream().map(p->{User u=users.selectById(p.getAuthorId());long cc=comments.selectCount(Wrappers.<ForumComment>lambdaQuery().eq(ForumComment::getPostId,p.getId()));Map<String,Object> m=new LinkedHashMap<>();m.put("id",p.getId());m.put("title",p.getTitle());m.put("content",p.getContent());m.put("category",p.getCategory());m.put("author",u==null?"未知用户":u.getNickname());m.put("views",p.getViewCount());m.put("likes",p.getLikeCount());m.put("comments",cc);m.put("createdAt",p.getCreatedAt());return m;}).toList();}
 @Transactional public ForumPost post(Long uid,Requests.PostCreate r){ForumPost p=new ForumPost();p.setAuthorId(uid);p.setCategory(r.category());p.setTitle(r.title());p.setContent(r.content());p.setLikeCount(0);p.setViewCount(0);p.setCreatedAt(OffsetDateTime.now());p.setUpdatedAt(OffsetDateTime.now());posts.insert(p);return p;}
 @Transactional public ForumComment comment(Long uid,Long postId,String content){if(posts.selectById(postId)==null)throw new BusinessException("帖子不存在");ForumComment c=new ForumComment();c.setPostId(postId);c.setAuthorId(uid);c.setContent(content);c.setCreatedAt(OffsetDateTime.now());comments.insert(c);return c;}
}
